name: cryptomoney
description: "Test Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  either_dart: ^1.0.0
  collection: ^1.19.1
  equatable: ^2.0.7
  provider: ^6.1.5
  rxdart: ^0.28.0
  flutter_svg: ^2.2.0
  flutter_dotenv: ^5.2.1
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - crypto.env
  fonts:
    - family: SFText
      fonts:
        - asset: fonts/SF-Pro.ttf